name: Validate Terraform Code

on:
  pull_request:
    types:
      - opened
      - synchronize

permissions:
  id-token: write
  contents: read

env:
  TF_IN_AUTOMATION: true
  TF_LOG: INFO
  TF_LOG_PROVIDER: ERROR
  TF_INPUT: false

jobs:
  terraform:
    name: 'Validate Terraform Code'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.11.2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: us-east-1
          role-session-name: GitHubActions-${{ github.run_id }}
          role-duration-seconds: 3600

      - name: Terraform Init
        run: terraform init

      - name: Terraform Format Check
        run: terraform fmt -check

      - name: Terraform Validate
        id: validate
        if: (success() || failure())
        run: terraform validate
