name: Terraform Dispatch Deployment to AWS

on:
  workflow_dispatch:
    inputs:
      destroy:
        description: "Set true to destroy the environment"
        required: false
        default: "false"
        type: choice
        options:
          - "false"
          - "true"

permissions:
  id-token: write
  contents: read

env:
  TF_IN_AUTOMATION: true
  TF_LOG: INFO
  TF_LOG_PROVIDER: ERROR
  TF_INPUT: false

jobs:
  terraform:
    name: "Terraform Apply"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.11.2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: me-south-1
          role-session-name: GitHubActions-${{ github.run_id }}
          role-duration-seconds: 3600

      - name: Terraform Init
        run: terraform init

      - name: Select or Create Workspace
        run: |
          if [[ "${{ github.ref_name }}" == "staging" ]]; then
            WS="staging"
          elif [[ "${{ github.ref_name }}" == "production" ]]; then
            WS="production"
          else
            echo "Error: This workflow must be run on 'staging' or 'production' branch."
            echo "Current branch: ${{ github.ref_name }}"
            exit 1
          fi

          echo "Workspace set to: $WS (derived from branch: ${{ github.ref_name }})"

          if ! terraform workspace list | grep -qw "$WS"; then
            terraform workspace new "$WS"
          else
            terraform workspace select "$WS"
          fi

      - name: Set DB password for workspace
        run: |
          if [[ "${{ github.ref_name }}" == "staging" ]]; then
            echo "TF_VAR_db_password=${{ secrets.STAG_DB_PASSWORD }}" >> $GITHUB_ENV
          elif [[ "${{ github.ref_name }}" == "production" ]]; then
            echo "TF_VAR_db_password=${{ secrets.PROD_DB_PASSWORD }}" >> $GITHUB_ENV
          else
            echo "Error: Branch is not staging or production. Cannot set DB password for branch ${{ github.ref_name }}."
            exit 1
          fi

      - name: Terraform Apply or Destroy
        run: |
          if [[ "${{ github.event.inputs.destroy }}" == "true" ]]; then
            terraform destroy -auto-approve
          else
            terraform apply -auto-approve
          fi
