name: Push Terraform Workspaces to AWS

on:
  workflow_call:
  # TODO: Uncomment this when we have a prod environment
  # push:
  #   branches: [dev, main]

env:
  TF_IN_AUTOMATION: true
  TF_LOG: INFO
  TF_LOG_PROVIDER: ERROR
  TF_INPUT: false

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.11.2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: eu-central-1
          role-session-name: GitHubActions-${{ github.run_id }}
          role-duration-seconds: 3600

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        if: github.ref == 'refs/heads/dev' || github.ref == 'refs/heads/prod'
        run: |
          if [[ $GITHUB_REF == "refs/heads/dev" ]]; then
            terraform workspace select dev
            terraform apply -auto-approve
          elif [[ $GITHUB_REF == "refs/heads/prod" ]]; then
            terraform workspace select prod
            terraform apply -auto-approve
          fi
