name: Push Terraform Workspaces to AWS

on:
  workflow_call:
  # push:
  #   branches: [staging, main]

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.11.2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: me-south-1
          role-session-name: GitHubActions-${{ github.run_id }}
          role-duration-seconds: 3600

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        if: github.ref == 'refs/heads/staging' || github.ref == 'refs/heads/production'
        run: |
          if [[ $GITHUB_REF == "refs/heads/staging" ]]; then
            terraform workspace select staging
            terraform apply -auto-approve
          elif [[ $GITHUB_REF == "refs/heads/production" ]]; then
            terraform workspace select production
            terraform apply -auto-approve
          fi
